schema:
  required_fields:
    Activity Label: string
    Activity Unit: string
    Scope: int
    Quantity: int
    GHG Category: string

  optional_fields:
    EF CO2: int64
    EF ID CO2: int64
    Taxonomy: string
    Global Region: string
    Country: string
    Region: string
    CO2AI Taxonomy: string
    Category: string

  custom_fields:
    Label Mandatory: string
    Label Forbidden: string
    Very Custom: string
    GBU: string
    SAP ID: int
    Data Source: string
    Supplier Name: string

sheets:
  - "Materials"
  - "Transportation"
  - "Waste"

use_preset_ef: True

default_taxonomies:
  Glass Sourcing: "level 3"
  Ingredient Sourcing: "level 3"
  Transport: "level 3"
  Use And End Of Life: "level 3"
