schema:
  required_fields:
    Activity Label: string
    Activity Unit: string
    Scope: int
    Quantity: int
    GHG Category: string

  optional_fields:
    EF CO2: int64
    EF ID CO2: int64
    Taxonomy: string
    Global Region: string
    Country: string
    Region: string
    CO2AI Taxonomy: string
    Category: string

  custom_fields:
    Label Mandatory: string
    Very Custom: string
    GBU: string
    SAP ID: int
    Data Source: string

  forbidden_fields:
    - "Label Forbidden"

sheets:
  - "Materials"
  - "Transportation"
  - "Waste"

use_preset_ef: False
